# define BINDER_MATCH "/usr/IFLib/data/binder/match"
# define BINDER_MATCH_CONTEXT "/usr/IFLib/data/binder/match_context"

# define BINDER_SUCCESS 100
# define BINDER_NO_MATCH 315
# define BINDER_TOO_DARK 316
# define BINDER_FRACTION 317
# define BINDER_BAD_FRACTION 318
# define BINDER_BAD_ENVIRONMENT 319
# define BINDER_NOT_LIVING 320
# define BINDER_AMBIGUOUS 322
# define BINDER_NOT_ENOUGH 323

# define BINDER_MATCH_SINGULAR 4
# define BINDER_MATCH_PLURAL  16

# define BINDER_MATCH_EXISTENCE 1
# define BINDER_MATCH_PLAYER 2
# define BINDER_SLOPPY_MATCHING 4
# define BINDER_MATCH_LIVING 8
# define BINDER_MATCH_WIELDED 16
# define BINDER_MATCH_WORN 32
# define BINDER_MATCH_DISTANT 64
# define BINDER_MATCH_IN_INVENTORY 128

# define EVERY_NUM 2147483647

# define BINDER_MATCH_TYPE 0
# define BINDER_MATCH_OBJECTS 1
