# define ACTOR_SEE 1
# define ACTOR_SMELL 2
# define ACTOR_TOUCH 4
# define ACTOR_TASTE 8
# define ACTOR_HEAR 16

# define ACTOR_MANIPULATE 128
# define ACTOR_COMBAT     256
# define ACTOR_MOVE       512

# define ACTOR_STANDING 1024
# define ACTOR_SITTING  2048
# define ACTOR_LYING    4096
# define ACTOR_FLYING   8192
# define ACTOR_LEANING  16384
# define ACTOR_KNEELING 32768
# define ACTOR_FLOATING 65536
# define ACTOR_SWIMMING 131070

# define RESP_AIR 1
# define RESP_WATER 2
# define RESP_VACUUM 4
# define RESP_METHANE 8

# define SEASON_SPRING 1
# define SEASON_SUMMER 2
# define SEASON_FALL 4
# define SEASON_WINTER 8
# define SEASON_DIURNAL 16
# define SEASON_NOCTURNAL 32

# define WEATHER_SNOWING 1
# define WEATHER_RAINING 2
# define WEATHER_CLOUDY  4

# define ARG_DIRECT_OBJ 1
# define ARG_INDIRECT_OBJ 2
# define ARG_IMPLEMENT_OBJ 4
# define ARG_COMMUNICATION 8

# define ARG_LIVING  1
# define ARG_PLAYER  2
# define ARG_DISTANT 4
# define ARG_WIELDED 8
# define ARG_WORN    16
# define ARG_IN_INVENTORY 32
# define ARG_IN_DIRECT_OBS 64
