# define WORD_LIST 1
# define STRING 2
# define OPTIONAL 3
# define DIRECT_OBJECT 4
# define INDIRECT_OBJECT 5
# define NUMBER 6
# define LIVING 7
# define SINGLE_WORD 8
# define DISTANT_LIVING 9
# define ANY_LIVING 10
# define ANY_OBJECT 11
# define SHORT_STRING 12
# define FRACTION 13
# define WIZ_PRESENT_TARGET 14
# define WORD_LIST_SPACES 15
# define OPTIONAL_SPACES 16
# define TARGET_PLAYER 17
# define QUOTED_STRING 18
# define PLURAL 32

# define ENV_ME_HERE 1
# define ENV_HERE 2
# define ENV_ME 3
# define ENV_HERE_ME 4
# define ENV_CLOSE 5
# define ENV_ON 6
# define ENV_NEAR 7
# define ENV_DIRECT_OBS 8
