# define ACTOR_SEE 1
# define ACTOR_SMELL 2
# define ACTOR_TOUCH 4
# define ACTOR_TASTE 8
# define ACTOR_HEAR 16

# define ACTOR_MANIPULATE 128
# define ACTOR_FIGHT      256

# define ACTOR_STANDING 1024
# define ACTOR_SITTING  2048
# define ACTOR_LYING    4096
# define ACTOR_FLYING   8192
# define ACTOR_LEANING  16384
# define ACTOR_KNEELING 32768
# define ACTOR_FLOATING 65536
# define ACTOR_SWIMMING 131070

# define RESP_AIR 1
# define RESP_WATER 2
# define RESP_VACUUM 4
# define RESP_METHANE 8

# define SEASON_SPRING 1
# define SEASON_SUMMER 2
# define SEASON_FALL 4
# define SEASON_WINTER 8
# define SEASON_DIURNAL 16
# define SEASON_NOCTURNAL 32

# define TERRAIN_UNDERGROUND 1
# define TERRAIN_BIOLOGICAL  2
# define TERRAIN_ROAD        4
# define TERRAIN_UNDERWATER  8
# define TERRAIN_SURFACE    16
# define TERRAIN_MIDAIR     32
# define TERRAIN_SWAMP      64
# define TERRAIN_WOODS     128
# define TERRAIN_JUNGLE    256
# define TERRAIN_ROUGH     512
# define TERRAIN_SEAFLOOR 1024
# define TERRAIN_OUTDOORS 2048
# define TERRAIN_INDOORS  4096
# define TERRAIN_SPACE    8192
# define TERRAIN_MAGMA   16384
# define TERRAIN_PLASMA  32768
# define TERRAIN_PLANAR  65536
# define TERRAIN_SNOW   131070
# define TERRAIN_SAND   262140
# define TERRAIN_ICE    524280
# define TERRAIN_WATERSHALLOW  1048560
# define TERRAIN_INDOORSWINDOW 2097120
# define TERRAIN_ROOFTOP       4194240

# define TERRAIN_ALL_OUTDOORS (TERRAIN_ROAD|TERRAIN_SWAMP|TERRAIN_WOODS|TERRAIN_JUNGLE|TERRAIN_ROUGH|TERRAIN_OUTDOORS|TERRAIN_SNOW|TERRAIN_SAND|TERRAIN_ICE|TERRAIN_ROOFTOP|TERRAIN_WATERSHALLOW)
# define TERRAIN_ALL_INDOORS (TERRAIN_UNDERGROUND|TERRAIN_INDOORS|TERRAIN_INDOORSWINDOW)
# define TERRAIN_ALL_WATER (TERRAIN_UNDERWATER|TERRAIN_SURFACE|TERRAIN_WATERSHALLOW|TERRAIN_SEAFLOOR)
# define TERRAIN_SEE_WEATHER (TERRAIN_ALL_OUTDOORS|TERRAIN_INDOORSWINDOW|TERRAIN_WATERSHALLOW|TERRAIN_SURFACE|TERRAIN_MIDAIR)

# define WEATHER_SNOWING 1
# define WEATHER_RAINING 2
# define WEATHER_CLOUDY  4
