#
# This parses the string templates in messages and such
#

# For now, most of the {{...}} pieces are commented out since they aren't 
# quite right yet.

message : bits

bits : bit
bits : bits ws bit

bit : words
bit : command
bit : pos

words : _
words : word
words : words word ? _combine_words

command : start_command command_ end_command ? _pass_second

command_ : if
command_ : if_else
command_ : choose_one

if : '#if' _ expression ws end_command bits start_command '/if' ? _if

if_else : '#if' _ expression ws end_command bits start_command '#else' end_command bits start_command '/if' ? _if_else

#unless : '#unless' _ expression ws end_command bits start_command '/unless' ? _unless

choose_one : '#chooseOne' word_list ? _choose_one_word
choose_one : '#chooseOne' property ? _choose_one_value

expression : property
expression : true_
expression : false_

word_list : words ? _create_word_list
word_list : word_list bar words ? _append_word_list

property : colon_name ? _default_property
property : expression point colon_name ? _exp_property

pos : bos pos_ eos ? _pass_second

pos_ : word  ? _simple_substitution
pos_ : word colon word ? _targeted_substitution

word : _word
word : false_
word : true_

false_ : 'false'
true_ : 'true'

ws :
ws : _ ? _noop

_word = /[^ #{}<>\b\n\t]+/

_ = /[ \b\n\t]*/

start_command = /{{/
end_command = /}}/

point = /[.]/

bos = /</
eos = />/

bar = /[ \b\n\t]*[|][ \b\n\t]*/

colon = /:/

colon_name = /[a-z]+(-[a-z]+)*(:[a-z]+(-[a-z]+)*)*/

