# define DECLARATION_DATA "/usr/ToolLib/data/parser/event_script/declarations"
# define EVENT_HANDLER_DATA  "/usr/ToolLib/data/parser/event_script/event_handler"
# define STATEMENTS_DATA "/usr/ToolLib/data/parser/event_script/statements"
# define CONSTANT_DATA "/usr/ToolLib/data/parser/event_script/constant"
# define CONSTANT_STATEMENT_DATA "/usr/ToolLib/data/parser/event_script/constant_statement"
# define IF_ELSE_DATA "/usr/ToolLib/data/parser/event_script/if_else"
# define DO_WHILE_DATA "/usr/ToolLib/data/parser/event_script/do_while"
# define FOR_DATA "/usr/ToolLib/data/parser/event_script/for"
# define CATCH_DATA "/usr/ToolLib/data/parser/event_script/catch"
# define SWITCH_DATA "/usr/ToolLib/data/parser/event_script/switch"
# define CASE_DATA "/usr/ToolLib/data/parser/event_script/case"
# define CASE_RANGE_DATA "/usr/ToolLib/data/parser/event_script/case_range"
# define RETURN_DATA "/usr/ToolLib/data/parser/event_script/return"
# define MESSAGE_DATA "/usr/ToolLib/data/parser/event_script/message"

# define CONTEXT_DATA "/usr/ToolLib/data/parser/event_script/context"
